### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by urcades** [new-computers/web#7]
@callil It's looking like the site is broken on http(s), perhaps this is a homebase/dns issue?

The site appears to be doing very well on beaker/.dat though:

dat://newcomputers.group/

lmk if I can help in any way

**Comment by callil** [comment]
I fixed this (had upgraded from httpd to hombase) 

Can someone verify and close if it's working? Should be more stable now too.

**Comment by ctogden** [comment]
Yes, it works now.
